### ISSUE TITLE
App doesn't load when protocol not specified.

### ISSUE THREAD

**Issue by matan157** [Alsciende/fiveringsdb#22]
When you try to open the page without `https://`, it loads with a js error in the console.

<img width="1221" alt="2017-09-03 at 9 20 15 pm" src="https://user-images.githubusercontent.com/8881055/30008439-b722fb18-90ed-11e7-92ef-ae2c6d4ecc9f.png">

**Comment by Alsciende** [comment]
Can you refresh your cache?

**Comment by matan157** [comment]
Refreshed cache, no change.

**Comment by drjimmie1976** [comment]
Same issue here - looks like a git conflict marker has been left in the code

**Comment by Alsciende** [comment]
Are you still experiencing the same issue? @matan157 @drjimmie1976

**Comment by drjimmie1976** [comment]
@Alsciende yes, if I hit the site 1) without specifying protocol 2) specifically with http I get the same error message as @matan157 

```
Uncaught Error: Module build failed: SyntaxError: Unexpected token (47:0)

  45 |       component: BuilderEditor,
  46 |       props: false,
> 47 | <<<<<<< HEAD
     | ^
  48 | =======
  49 |     },
  50 |     {


    at Object.158 (app.32962963d109b103a79f.js:67)
    at n (bootstrap 4abea043e5e86f27e41c:54)
    at Object.179 (app.32962963d109b103a79f.js:490)
    at n (bootstrap 4abea043e5e86f27e41c:54)
    at window.webpackJsonp (bootstrap 4abea043e5e86f27e41c:25)
    at app.32962963d109b103a79f.js:1
```

You can see that a git conflict marker has been left in one of your source files, causing a runtime Syntax Error. If you strip that out it might fix it? I'll pull the source later and try to track it down.

**Comment by Alsciende** [comment]
Can you retry? I removed some leftover files.

**Comment by Alsciende** [comment]
Anyway, it doesn't change the fact that you shouldn't even be able to request with http. There's a proxy cache somewhere that messes things up.

**Comment by drjimmie1976** [comment]
Working on https but getting a 404 without.

Couldn't find the conflict marker in the code on `master`, I think it was from index.js but looks like it has been cleaned up.

**Comment by Alsciende** [comment]
Is it fixed now?

**Comment by drjimmie1976** [comment]
Yes, all HTTP or unspecified requests are redirecting to HTTPS.

I think I originally found the site through Reddit, and the link didn't specify the protocol. Cheers!

**Comment by drjimmie1976** [comment]
PS great work with all these sites, they are a fantastic player resource.

**Comment by Alsciende** [comment]
Thank you for your help debugging the issue :)
