### ISSUE TITLE
Adding card to deck invalidates, but does not clear, filter

### ISSUE THREAD

**Issue by stoppableforce** [Alsciende/fiveringsdb#23]
Steps to reproduce:

1. Build a new deck. In my specific case, I was building a Dragon deck, so I had selected the Dragon stronghold, the Keeper of Void role, and five provinces.
2. Use the buttons so you you are only displaying Dragon and Neutral Characters.
3. This still shows Conflict deck characters, so in the filter box, type "d:dynasty". (Feature suggestion, while we're at it: Separate the characters button into 'dynasty characters' and 'conflict characters').
4. At this point, only Dynasty characters from Dragon and Neutral are shown. Add a character to the deck - I added 3 Togashi Yokuni.
5. The filter box will still say "d:dynasty," but Conflict deck characters will reappear in the list of cards.

**Comment by Alsciende** [comment]
Thank you for your perfect bug reports @stoppableforce  :)
