### ISSUE TITLE
Cannot always change number of cards in deck by clicking card

### ISSUE THREAD

**Issue by stoppableforce** [Alsciende/fiveringsdb#25]
When I am creating a deck, if I click a card that is in my deck, I get a popup showing me the card art and text, but cannot change how many copies of that card are in my deck - the 0/1/2/3 buttons do not appear.

When I am _editing_ an existing deck, if I click a card that is in my deck, I get a popup showing me the cart art and text, and am able to change how many copies of that card are in my deck by clicking 0, 1, 2, or 3.

To replicate:

1. Create a new deck in the deckbuilder.
2. Add 1 or more copies of a card to the deck.
3. Click the card name in the decklist - 0/1/2/3 are not in the popup. 
4. Click the card name in the list of available cards - 0/1/2/3 are not in the popup.
5. Save the deck.
6. Click "Deckbuilder" to return to the list of decks, click "View" next to the deck you just created, then click "Edit."
7. Click the card name in the decklist - 0/1/2/3 _are_ in the popup.
8. Click the card name in the list of available cards - 0/1/2/3 _are_ in the popup.

**Comment by Alsciende** [comment]
Correction deployed
