### ISSUE TITLE
Card subtypes do not update when changing pages

### ISSUE THREAD

**Issue by hbarsquared** [Alsciende/fiveringsdb#5]
When you click to the next page, the card subtypes don't update. For example, the first card on page one (Above Question) is a Crane Attachment, Condition.  The first card on page 2 (For Greater Glory) also reads Crane Attachment, Condition, which is incorrect.
![image](https://user-images.githubusercontent.com/29467489/27201758-6f9184f6-51e4-11e7-86ae-a59c7ab531d2.png)

**Comment by Alsciende** [comment]
I don't reproduce that issue. Just to be sure, can you clear your browser cache and retry?
